# Generated by Django 4.1 on 2022-09-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('brend', models.CharField(max_length=200)),
                ('miqdor', models.IntegerField()),
                ('kelgan_narx', models.BigIntegerField()),
                ('sotuv_narx', models.BigIntegerField()),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('dokon', models.CharField(max_length=50)),
                ('manzil', models.TextField()),
                ('qarz', models.IntegerField(default=0)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
    ]
