# Generated by Django 4.1 on 2022-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='manzil',
            field=models.CharField(max_length=200),
        ),
    ]
