# Generated by Django 4.1 on 2022-09-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dokon_nomi',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='users',
            name='manzil',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ombor',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tel',
        ),
    ]
