# Generated by Django 4.1 on 2022-09-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_users_dokon_nomi_remove_users_ism_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
